service: final-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1


functions:
  trigger:
    handler: src/handler
    events:
      - http:
          path: hello
          method: get
