name: AWS Job

on:
  push:
    branches:
      - test-field

jobs:
  aws-job:
    runs-on: ubuntu-latest
    steps:
      - name: List Repository Contents
        run: |
          ls ${{ github.workspace }}

      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Check if AWS CLI is installed
        run: |
          aws --version

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform version
        run: terraform version

      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
        env:
          super_secret: ${{ secrets.AWS_CONFIG }}

          

      - name: Display AWS credentials
        run: cat ~/.aws/credentials

      - name: List AWS profiles
        run: aws configure list-profiles

      - name: List S3 buckets
        run: aws s3 ls --region eu-central-1 --profile techstarter
    
