name: 'Build and upload to S3 Bucket'

on:
  push:
    branches:
      - test-field

jobs:
  Build_and_Upload:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Generate Tag Version'
        id: generate_tag_version
        run: |
          TAG=$(date +%Y%m%d)-$(date +%H%M%S)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Tag Version: $TAG" >> $GITHUB_STEP_SUMMARY
    
      - name: 'Create Zip File'
        id: 'create_package'
        run: |
          PACKAGE_NAME="${{ steps.generate_tag_version.outputs.tag }}.zip"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          cd lambda-functions  # Assuming your Lambda functions are in a directory called "lambda-functions"
          zip -r $GITHUB_WORKSPACE/$PACKAGE_NAME .

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws/
          echo "[techstarter]" > ~/.aws/config
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      - name: Show AWS credentials
        run: cat ~/.aws/config

      - name: List S3 buckets
        run: aws s3 ls --region eu-central-1 --profile

      - name: 'Upload to S3 Bucket'
        run: aws s3 cp $GITHUB_WORKSPACE/${{ steps.create_package.outputs.package_name }} s3://tfstate-bucket-abschlussproject1/

      - uses: actions/github-script@v6
        name: 'Create Git Tag'
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.generate_tag_version.outputs.tag }}',
              sha: context.sha
            })
