name: Deploy to S3 Bucket

on:
  push:
    branches:
      - test-field

jobs:
  deploy_source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Show AWS credentials
        run: cat ~/.aws/config


        

      # - name: Zip
      #   uses: montudor/action-zip@v0.1.0
      #   with:
      #     args: zip -qq -r ./bundle.zip ./

      # - name: Deploy Lambda Functions
      #   run: |
      #     cd lambda-functions/
      #     for FUNCTION_DIR in */; do
      #       FUNCTION_NAME=$(basename $FUNCTION_DIR)
      #       echo "Deploying Lambda function: $FUNCTION_NAME"
            
      #       # Adjust the following line according to your deployment needs
      #       aws s3 cp ./bundle.zip s3://tfstate-bucket-abschlussproject1/$FUNCTION_NAME/bundle.zip
      #       aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket tfstate-bucket-abschlussproject1 --s3-key $FUNCTION_NAME/bundle.zip
      #     done
          
