name: Build and Deploy Lambda Functions

on:
  push:
    branches:
      - test-field

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: full

      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws/
          echo "$AWS_CONFIG" > ~/.aws/config
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1
        env:
          AWS_CONFIG: ${{ secrets.AWS_CONFIG }}

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: [configure-aws]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: full

      - name: Create Build Directory
        run: mkdir -p $GITHUB_WORKSPACE/build

      - name: Zip and Deploy Lambda Functions
        run: |
          S3_BUCKET=tfstate-bucket-abschlussproject1
          LAMBDA_FUNCTION_DIR=lambda-functions
          S3_KEY=lambda-function.zip

          aws s3 sync ./build s3://tfstate-bucket-abschlussproject1/ --delete --acl public-read --region eu-central-1

      - name: Execute Deployment Script
        run: |
          for FUNCTION_DIR in $LAMBDA_FUNCTION_DIR/*; do
            if [ -d "$FUNCTION_DIR" ]; then
              LAMBDA_FUNCTION_NAME=$(basename $FUNCTION_DIR)

              # Zip the Lambda function
              (cd $LAMBDA_FUNCTION_DIR && zip -r $GITHUB_WORKSPACE/build/$LAMBDA_FUNCTION_NAME.zip $LAMBDA_FUNCTION_NAME)

              # Upload the zip file to S3
              aws s3 cp $GITHUB_WORKSPACE/build/$LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET/$LAMBDA_FUNCTION_NAME/$S3_KEY

              # Update the Lambda function code
              echo "Updating Lambda function: $LAMBDA_FUNCTION_NAME"
              aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $LAMBDA_FUNCTION_NAME/$S3_KEY

              # Cleanup
              rm $GITHUB_WORKSPACE/build/$LAMBDA_FUNCTION_NAME.zip
            fi
          done
