name: Deploy Ansible

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Ansible Playbook
        uses: ./.github/actions/ansible
        with:
          playbook: docker/playbook.yml
          inventory: localhost
