name: Build and Deploy Lambda Functions

on:
  push:
    branches:
      - test-field

jobs:
  configure-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: full

      - name: Configure AWS CLI
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
          echo "AWS_CONFIG_FILE=$GITHUB_WORKSPACE/.aws/config" >> $GITHUB_ENV
          echo "AWS_SHARED_CREDENTIALS_FILE=$GITHUB_WORKSPACE/.aws/credentials" >> $GITHUB_ENV


  deploy-lambda:
  runs-on: ubuntu-latest
  needs: [configure-aws]

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: full

    - name: Configure AWS CLI
      run: |
        echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
        echo "AWS_CONFIG_FILE=$GITHUB_WORKSPACE/.aws/config" >> $GITHUB_ENV
        echo "AWS_SHARED_CREDENTIALS_FILE=$GITHUB_WORKSPACE/.aws/credentials" >> $GITHUB_ENV

    - name: Zip and Deploy Lambda Functions
      run: |
        S3_BUCKET=tf-backend-abschlussprojekt
        LAMBDA_FUNCTION_DIR=lambda-functions
        S3_KEY=lambda-function.zip

        for FUNCTION_DIR in $LAMBDA_FUNCTION_DIR/*; do
          if [ -d "$FUNCTION_DIR" ]; then
            LAMBDA_FUNCTION_NAME=$(basename $FUNCTION_DIR)

            # Zip the Lambda function
            zip -r $GITHUB_WORKSPACE/$LAMBDA_FUNCTION_NAME.zip -C $LAMBDA_FUNCTION_DIR $LAMBDA_FUNCTION_NAME

            # Upload the zip file to S3
            aws s3 cp $GITHUB_WORKSPACE/$LAMBDA_FUNCTION_NAME.zip s3://$S3_BUCKET/$LAMBDA_FUNCTION_NAME/$S3_KEY

            # Update the Lambda function code
            aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $LAMBDA_FUNCTION_NAME/$S3_KEY

            # Cleanup
            rm $GITHUB_WORKSPACE/$LAMBDA_FUNCTION_NAME.zip
          fi
        done

        aws s3 sync ./build s3://tfstate-bucket-abschlussproject/ --delete --acl public-read --region eu-central-1

