name: Deploy to S3 Bucket

on:
  push:
    branches:
      - test-field

jobs:
  deploy_source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: |
      #     cd lambda-functions
      #     npm install
      #   env:
      #     CI: true


      - name: Configure AWS CLI
        run: |
          mkdir -p ~/.aws/
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/config
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
          echo "region = eu-central-1" >> ~/.aws/config
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
      - name: Show AWS credentials
        run: cat ~/.aws/config


          
